#!/bin/bash

installer="/data/altitude.sh"
target="/data/altitude"

if [ ! -f $installer ]
then
  curl "http://installer.altitudegame.com/0.0.1/altitude.sh" -o $installer
fi

if [ ! -x $installer ]
then
  chmod a+rx $installer
fi


if [ ! -d $target ]
then
  if [ -x $installer ] 
  then
    expect <<EOD
spawn sudo $installer -c
expect "Where should Altitude be installed?"
send "${target}\n"
expect "Create symlinks?"
send "y\n"
expect "Select the folder where you would like Altitude to create symlinks, then click Next."
send "\n"
expect "Create a desktop icon?"
send "n\n"
expect "Run Altitude?"
send "n\n"
expect "Finishing installation..."
exit 0
EOD
  else
    if [ -f $installer ]
    then
      echo "ERROR: ${installer} not executable"
      exit 1
    else
      echo "ERROR: ${installer} not found"
    fi
  fi
fi

# Start server
if [ -x ${target}/server_launcher ]
then
  until ${target}/server_launcher; do
    echo "Altitude server stopped with exit code $?.  Respawning.." >&2
    sleep 1
  done
else
  echo "ERROR: ${target}/server_launcher not found"
  exit 1
fi
