#!/bin/bash

# Define locations
installer="/data/altitude.sh"
target="/data/altitude"

# Get installer file
if [ ! -f $installer ]
then
  curl "http://installer.altitudegame.com/0.0.1/altitude.sh" -o $installer
fi

# Make it read-/executable
if [ ! -x $installer ]
then
  chmod a+rx $installer
fi

# Run installer and use "expect" to answer questions.
if [ ! -d $target ]
then
  if [ -x $installer ] 
  then
    expect <<EOD
set timeout -1
spawn sudo $installer -c
expect "Where should Altitude be installed?"
send "${target}\n"
expect "Create symlinks?"
send "y\n"
expect "Select the folder where you would like Altitude to create symlinks, then click Next."
send "\n"
expect "Create a desktop icon?"
send "n\n"
expect "Run Altitude?"
send "n\n"
expect "Finishing installation..."
exit 0
EOD
  else
    if [ -f $installer ]
    then
      echo "ERROR: ${installer} not executable"
      exit 1
    else
      echo "ERROR: ${installer} not found"
    fi
  fi
fi

# Start server
while true
do
  if [ -x ${target}/server_launcher ]
  then
    ${target}/server_launcher
  else
    echo "ERROR: ${target}/server_launcher not found or not executable"
    exit 1
  fi
  sleep 1
done
